### ISSUE TITLE
Linking error with v2.6

### ISSUE THREAD

**Issue by Hung-Hsun** [chebur/pjsip#48]
I use Cocoapods to update this pod to v2.6, and build with Xcode8.3.2 in OSX10.12.4, and got the following error:

Undefined symbols for architecture armv7:
  "_SSL_is_server", referenced from:
      _set_curves_list in libpj-apple-darwin_ios.a(ssl_sock_ossl.o)
  "_EC_curve_nid2nist", referenced from:
      _init_openssl in libpj-apple-darwin_ios.a(ssl_sock_ossl.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can anyone tell me how to fix this? Thank you very much!

**Comment by apolovinka** [comment]
Had the same issue. Following the #47 description you have to update the OpenSSL-Universal pod to the most recent version.

**Comment by Hung-Hsun** [comment]
@apolovinka Thank you so much. I add the following line shown in #47 to my podfile, and the problem is fixed.

`pod 'OpenSSL-Universal', :git => 'https://github.com/krzyzanowskim/OpenSSL.git', :branch => :master`
