### ISSUE TITLE
Can't compile on version 2.6.0

### ISSUE THREAD

**Issue by fedetrim** [chebur/pjsip#52]
I have a very small and isolated project that makes use of pjsip. I can compile perfectly using this pod, except on version 2.6.0. The error is:

```
Undefined symbols for architecture x86_64:
  "_SSL_is_server", referenced from:
      _create_ssl in libpj-apple-darwin_ios.a(ssl_sock_ossl.o)
  "_EC_curve_nid2nist", referenced from:
      _init_openssl in libpj-apple-darwin_ios.a(ssl_sock_ossl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

With version 2.5.5.2 and lower, I have no problems.

**Comment by BMatthai** [comment]
Same problem, (except in my case it is for architecture arm64). 
Perfectly works on version 2.5.5.2 but same error in 2.6

**Comment by luizdias** [comment]
Same problem here, version 2.6.0, tested today.

**Comment by Sakash** [comment]
Same problem i also faced,then i have to degrade pod PJSIP library version to 2.5.5.2
<img width="311" alt="screen shot 2017-08-09 at 5 37 16 pm" src="https://user-images.githubusercontent.com/5800576/29120761-74b2d03c-7d29-11e7-8ab8-6e47f71cfe8d.png">

**Comment by SharePeng** [comment]
show to fix this problem?who can help ?

**Comment by BMatthai** [comment]
Hello,


Here is the solution :

https://github.com/chebur/pjsip/issues/48

Bye,

Bastien

________________________________
De : SharePeng <notifications@github.com>
Envoyé : mardi 5 septembre 2017 08:24
À : chebur/pjsip
Cc : BMatthai; Comment
Objet : Re: [chebur/pjsip] Can't compile on version 2.6.0 (#52)


show to fix this problem?who can help ?

**Comment by SharePeng** [comment]
hello,I fix that problem.but ,console show this "RTP decode error: Invalid RTP version",it works on 2.5.5

**Comment by chebur** [comment]
compilation error was fixed in #47 
also the binaries were update to pjsip 2.8
